version: '3'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fineract_tenants
      MYSQL_USER: fineract
      MYSQL_PASSWORD: fineract
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mifos-network
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  fineract:
    build:
      context: ./fineract
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - mysql
    environment:
      - FINERACT_DATASOURCE_HOST=mysql
      - FINERACT_DATASOURCE_PORT=3306
      - FINERACT_DATASOURCE_DB_NAME=fineract_tenants
      - FINERACT_DATASOURCE_USERNAME=fineract
      - FINERACT_DATASOURCE_PASSWORD=fineract
      - FINERACT_DEFAULT_TENANTDB_PORT=3306
      - FINERACT_DEFAULT_TENANTDB_HOST=mysql
      - FINERACT_DEFAULT_TENANTDB_USERNAME=fineract
      - FINERACT_DEFAULT_TENANTDB_PASSWORD=fineract
    ports:
      - "8443:8443"
    networks:
      - mifos-network

  mifos:
    image: openmf/community-app:latest
    platform: linux/amd64
    depends_on:
      - fineract
    networks:
      - mifos-network
    ports:
      - "9090:80"

  nginx:
    image: nginx:latest
    platform: linux/amd64
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - ./certs/selfsigned.key:/etc/ssl/private/selfsigned.key:ro
    ports:
      - "443:443"
    depends_on:
      - mifos
    networks:
      - mifos-network

volumes:
  mysql_data:

networks:
  mifos-network:
    driver: bridge